title: 영농형태양광과 스마트에너지그리드(작성중)
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://smartorchard.github.io/agrivoltaic-grid/

aux_links:
  Template Repository: https://github.com/smartorchard/agrivoltaic-grid
